# Generated by Django 5.0.1 on 2024-01-04 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="phone_no",
            new_name="phone",
        ),
    ]
