# Generated by Django 5.0.1 on 2024-01-04 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_phone_no_contact_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="Name",
            new_name="name",
        ),
    ]
